name: Build, Test, and Publish NuGet

on:
  push:
    branches: [ "main" ]
jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install NPM Packages
      working-directory: ./src/LexiCore.Nuget/ClientApp
      run: npm ci
    - name: Run React Tests (Vitest)
      working-directory: ./src/LexiCore.Nuget/ClientApp
      run: npx vitest run
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x' # Update to 9.x if you upgrade
    - name: Restore .NET Dependencies
      run: dotnet restore
    - name: Build .NET Solution
      run: dotnet build --no-restore --configuration Release
    - name: Run C# Tests (xUnit)
      run: dotnet test --no-build --configuration Release --verbosity normal
    - name: Pack NuGet Package
      run: >
        dotnet pack ./src/LexiCore.Nuget/LexiCore.csproj
        --no-build
        --configuration Release
        --output ./nupkgs
    - name: Push to NuGet.org
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
